version: '3'
services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:80"
    networks:
      - laravel_network
    command: php artisan migrate --seed
    volumes:
      - apache_logs:/var/log/apache2
    depends_on:
      - db

#MySQL Service
  db:
    build: ./database
    container_name: db
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: laravel_password
      MYSQL_USER: laravel_user
    volumes:
      - dbdata:/var/lib/mysql/
      - dbcnf:/etc/my.cnf
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dbcnf:
    driver: local
  apache_logs:
    driver:local

